export enum TeamTags {
  DeFi = "DeFi",
  NFTs = "NFTs",
  Blockchain = "Blockchain",
  Gaming = "Gaming",
  "DAO Tooling" = "DAO Tooling",
  "Layer 2" = "Layer 2",
  "Wallet/Payments" = "Wallet/Payments",
  "Developer Tool" = "Developer Tool",
  "Data / Analytics" = "Data / Analytics",
  "Audio / Video" = "Audio / Video",
  "Social Network" = "Social Network",
  "Zero Knowledge" = "Zero Knowledge",
  "Metaverse" = "Metaverse",
  "Other" = "Other",
  "Smart Contracts" = "Smart Contracts",
  "Beginner Friendly" = "Beginner Friendly",
  "Experienced" = "Experienced",
}
